[fix] Update version

diff --git a/scripts/restore b/scripts/restore
--- a/scripts/restore
+++ b/scripts/restore
@@ -1,16 +1,66 @@
 #!/bin/bash
-app=minchat
 
-# The parameter $1 is the uncompressed restore directory location
-backup_dir=$1/apps/$app
+# causes the shell to exit if any subcommand or pipeline returns a non-zero status
+set -eu
+
+# Source app helpers
+source /usr/share/yunohost/helpers
+
+app=$YNH_APP_INSTANCE_NAME
+
+# Retrieve arguments
+domain=$(ynh_app_setting_get "$app" domain)
+path=$(ynh_app_setting_get "$app" path)
+user=$(ynh_app_setting_get $app allowed_users)
+is_public=$(ynh_app_setting_get $app is_public)
+
+# Check domain/path availability
+sudo yunohost app checkurl "${domain}${path}" -a "$app" \
+    || ynh_die "Path not available: ${domain}${path}"
+
+# Check $final_path
+final_path="/var/www/${app}"
+if [ -d $final_path ]; then
+	ynh_die "There is already a directory: $final_path"
+fi
+
+# Check configuration files
+nginx_conf="/etc/nginx/conf.d/${domain}.d/${app}.conf"
+if [ -f $nginx_conf ]; then
+	ynh_die "The NGINX configuration already exists at '${nginx_conf}'. 
+	You should safely delete it before restoring this app."
+fi
+# Check configuration files php-fpm
+phpfpm_conf="/etc/php5/fpm/pool.d/php-fpm-${app}.conf"
+if [ -f $phpfpm_conf ]; then 
+	ynh_die "The PHP FPM configuration already exists at '${phpfpm_conf}'. 
+	You should safely delete it before restoring this app."
+fi
+
+phpfpm_ini="/etc/php5/fpm/conf.d/20-${app}.ini"
+if [ -f $phpfpm_ini ]; then
+	ynh_die "The PHP FPM INI configuration already exists at '${phpfpm_ini}'. 
+	You should safely delete it before restoring this app."
+fi
 
 # Restore sources & data
-sudo cp -a $backup_dir/sources/. /var/www/$app
+sudo cp -a "./sources" $final_path
 
-# Restore Nginx and YunoHost parameters
-sudo cp -a $backup_dir/yunohost/. /etc/yunohost/apps/$app
-domain=$(sudo yunohost app setting $app domain)
-sudo cp -a $backup_dir/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf
+# Set permissions
+sudo chown -R $app: $final_path
 
-# Restart webserver
-sudo service nginx reload
+# Restore configuration files
+sudo cp -a ./conf/nginx.conf "${nginx_conf}"
+
+# Restore php-fpm configuration files
+sudo cp -a ./conf/php-fpm.conf "${phpfpm_conf}"
+sudo cp -a ./conf/php-fpm.ini "${phpfpm_ini}"
+
+# Set ssowat config
+if [[ $is_public -eq 0 ]]; then
+	ynh_app_setting_delete $app skipped_uris
+fi
+
+# Reload service
+sudo systemctl reload nginx
+sudo yunohost app ssowatconf
diff --git a/scripts/upgrade b/scripts/upgrade
--- a/scripts/upgrade
+++ b/scripts/upgrade
@@ -1,26 +1,58 @@
 #!/bin/bash
-app=minchat
 
-# Retrieve arguments
-domain=$(sudo yunohost app setting $app domain)
-path=$(sudo yunohost app setting $app path)
+# Exit on command errors and treat unset variables as an error
+set -eu
+# Source app helpers
+source ./_common
+source /usr/share/yunohost/helpers
+
+app=$YNH_APP_INSTANCE_NAME
+
+domain=$(ynh_app_setting_get "$app" domain)
+path=$(ynh_app_setting_get "$app" path)
+user=$(ynh_app_setting_get "$app" user)
+is_public=$(ynh_app_setting_get $app is_public)
+
+ynh_backup_before_upgrade	# Backup the current version of the app
+ynh_clean_setup () {
+	ynh_backup_fail_upgrade	# restore it if the upgrade fails
+}
+ynh_abort_if_errors	# Active trap pour arrêter le script si une erreur est détectée.
 
 # Remove trailing "/" for next commands
-path=${path%/}
-
-# Copy source files
-final_path=/var/www/$app
-sudo mkdir -p $final_path
-sudo cp -a ../sources/* $final_path
-if [[ ! -f ${final_path}/conf/setup.ini ]] ; then
-    sudo cp ${final_path}/conf/sample/setup.ini ${final_path}/conf/ 
+if [[ ! "$path" == "/" ]]; then
+    path=${path%/}
 fi
+
+# Create system user dedicace for this app
+ynh_system_user_create $app
+
+# Init final_path, if ever it got deleted somehow
+final_path=/var/www/$app
+
+# Clean all files and directory except the data directory 
+ynh_secure_remove $final_path
+
+# Create directory
+sudo mkdir -p $final_path
+
+# Copy files to the right place
+extract_source $final_path
+
+# Fix owner
+sudo chown -R $app: $final_path
+
 # Modify Nginx configuration file and copy it to Nginx conf directory
-sed -i "s@PATHTOCHANGE@$path@g"  ../conf/nginx.conf
-sed -i "s@WWWPATH@$final_path@g" ../conf/nginx.conf
-sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf
+ynh_nginx_config
 
-# Restart services
-sudo service nginx reload
+# Create the php-fpm pool config
+ynh_fpm_config
+
+# Set ssowat config
+if [[ $is_public -eq 1 ]]; then
+  ynh_app_setting_set "$app" unprotected_uris "/"
+fi
+
+# Reload Nginx
+sudo systemctl reload nginx
 sudo yunohost app ssowatconf
-
